### ISSUE TITLE
LICENSE file missing

### ISSUE THREAD

**Issue by crshrprt** [vanishady/PitchShifter#1]
Thank you for this interesting plugin.

I can't find if the source is released under a license. Is there a license?

**Comment by vanishady** [comment]
Hi, glad you liked it. It is free to use, no license 
all the plugins you find [here](https://audioplugins.lim.di.unimi.it/index.php?p=2&#p22) are developed in university and free

**Comment by crshrprt** [comment]
Thank you for the answer. I see the plugins are available for "free" on the LIM website. 
So, not having a LICENSE I guess it's not technically "free software" (free as in freedom) but "freeware" (free as in free beer)?

I see that some of the LIM's plugins are made with the JUCE framework, on the JUCE website there is the following [statement](https://juce.com/get-juce/):

> JUCE is dual licensed under both the JUCE licence and the AGPLv3.
> 
> This means that you can choose to use JUCE under the terms of the AGPLv3 licence. If you are not "propagating" or "conveying" closed-source software containing JUCE outside of your organisation then you may not be violating the terms of the AGPLv3. The creation and use of "in-house" tools and the internal development of "pre-release" software (before it goes out to external testers) is usually permitted under the AGPLv3. Please refer to the AGPLv3 terms for the full details.
> 
> If you are not using JUCE under the AGPLv3 then you will require a JUCE licence. You will need to maintain a licence for at least the duration over which you are distributing closed-source binaries containing JUCE.

I assume you are releasing your plugins made with JUCE with a JUCE license then, is that correct?

**Comment by vanishady** [comment]
Yes it is general public license

**Comment by crshrprt** [comment]
Thank you, that's really good news, if I understood correctly. 

If the plugins released by the students of LIM are GPL (at least those made with JUCE) why it's not stated anywhere?

It's a good practice to publish the code with the right license, without an explicit LICENSE one should assume, until proven otherwise, it's not free software. After all it's an University, why omitting the fact it's GPL and showcasing the plugins as they are "freeware"?

Anyway, thank you again for clarifying.

**Comment by vanishady** [comment]
You're right, I will upload now a GPL license to clarify ;) we all love open-source here, but i think some students may be just distracted and do not upload their code, plus the boundary between open-source and freeware is not very clear due to the fact it was developed in university (I was also not so sure if I could actually publish it either, but seems so).
